SELECT * FROM STAND_USER;

-- Question 1
SELECT AVG(POWER) AS "AVG_POWER", MAX(POWER) AS "MAX_POWER", MIN(POWER) AS "MIN_POWER"
FROM STAND_USER;

-- Question 2
SELECT COUNT(PRECISION) AS "KNOWN_PRECISION", COUNT(*) AS "TOTAL_USERS"
FROM STAND_USER;

-- QUestion 3
SELECT ROUND(STDDEV(POWER), 3) AS "STDDEV_POWER", ROUND(VARIANCE(POWER), 3) AS "VARIANCE_POWER"
FROM STAND_USER;

-- QUestion 4
SELECT PRECISION, AVG(POWER) AS "AVG_POWER"
FROM STAND_USER
WHERE PRECISION IS NOT NULL
GROUP BY PRECISION;

-- Question 5
SELECT PRECISION, AVG(POWER) AS "AVG POWER"
FROM STAND_USER
WHERE PRECISION IS NOT NULL
HAVING AVG(POWER) > 80
GROUP BY PRECISION;

-- Question 6 (Asked ChatGPT help and it said to do a subquery)
SELECT USER_NAME, STAND_NAME, ROUND(POWER - (SELECT AVG(POWER) FROM STAND_USER), 3) AS "DIFF_FROM_AVG"
FROM STAND_USER;

-- Question 7
SELECT ROUND(AVG(POWER), 2) AS "ROUNDED_AVG_POWER"
FROM STAND_USER;

-- Question 8 
SELECT PRECISION, SUM(POWER) AS "TOTAL_POWER"
FROM STAND_USER
GROUP BY ROLLUP(PRECISION);

-- QUestion 9
SELECT EXTRACT(YEAR FROM debut_date) AS debut_year,
       precision,
       SUM(power) AS total_power
FROM stand_user
GROUP BY CUBE(EXTRACT(YEAR FROM debut_date), precision)
ORDER BY debut_year, precision;